In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('/Users/andrewbadzioch/Desktop/MLB_stuff/data/pitcherStat2024.csv')

In [3]:
pitch = df.copy()
pitch.head()

,"last_name, first_name",player_id,year,player_age,p_game,p_formatted_ip,pa,ab,hit,single,...,blasts_contact,blasts_swing,squared_up_contact,squared_up_swing,avg_swing_length,swords,exit_velocity_avg,launch_angle_avg,sweet_spot_percent,barrel_batted_rate
0,"Fedde, Erick",607200,2024,31,31,177.1,726,661,154,100,...,13.4,10.6,33.4,26.5,7.2,15,88.6,14.9,32.4,7.6
1,"Taillon, Jameson",592791,2024,32,28,165.1,675,633,154,107,...,15.8,13.1,37.4,30.9,7.4,20,89.7,15.9,32.2,7.2
2,"López, Pablo",641154,2024,28,32,185.1,772,715,180,121,...,11.5,8.6,29.6,22.1,7.3,28,87.9,13.3,35.9,8.2
3,"Eflin, Zach",621107,2024,30,28,165.1,684,653,166,114,...,15.4,12.4,34.9,27.9,7.4,22,88.1,13.3,30.0,7.5
4,"Houck, Tanner",656557,2024,28,30,178.2,743,674,156,118,...,16.0,12.6,36.8,29.0,7.4,17,89.4,3.8,30.2,5.7

In [4]:
print("the shape of the dataset is: ", pitch.shape, '\n')
print("the size of the dataset is: ", pitch.size, '\n')
print("the columns of the dataset are: ", pitch.columns, '\n')

the shape of the dataset is:  (107, 39)

the size of the dataset is:  4173

the columns of the dataset are:  Index(['last_name, first_name', 'player_id', 'year', 'player_age', 'p_game',
       'p_formatted_ip', 'pa', 'ab', 'hit', 'single', 'double', 'triple',
       'home_run', 'strikeout', 'walk', 'k_percent', 'bb_percent',
       'batting_avg', 'slg_percent', 'on_base_percent', 'on_base_plus_slg',
       'xba', 'xslg', 'woba', 'xwoba', 'xobp', 'xiso', 'avg_swing_speed',
       'fast_swing_rate', 'blasts_contact', 'blasts_swing',
       'squared_up_contact', 'squared_up_swing', 'avg_swing_length', 'swords',
       'exit_velocity_avg', 'launch_angle_avg', 'sweet_spot_percent',
       'barrel_batted_rate'],
      dtype='object')

In [5]:
pitch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   last_name, first_name  107 non-null    object
 1   player_id              107 non-null    int64
 2   year                   107 non-null    int64
 3   player_age             107 non-null    int64
 4   p_game                 107 non-null    int64
 5   p_formatted_ip         107 non-null    float64
 6   pa                     107 non-null    int64
 7   ab                     107 non-null    int64
 8   hit                    107 non-null    int64
 9   single                 107 non-null    int64
 10  double                 107 non-null    int64
 11  triple                 107 non-null    int64
 12  home_run               107 non-null    int64
 13  strikeout              107 non-null    int64
 14  walk                   107 non-null    int64
 15  k_percent              107 non-null    float64
 16  bb_percent             107 non-null    float64
 17  batting_avg            107 non-null    float64
 18  slg_percent            107 non-null    float64
 19  on_base_percent        107 non-null    float64
 20  on_base_plus_slg       107 non-null    float64
 21  xba                    107 non-null    float64
 22  xslg                   107 non-null    float64
 23  woba                   107 non-null    float64
 24  xwoba                  107 non-null    float64
 25  xobp                   107 non-null    float64
 26  xiso                   107 non-null    float64
 27  avg_swing_speed        107 non-null    float64
 28  fast_swing_rate        107 non-null    float64
 29  blasts_contact         107 non-null    float64
 30  blasts_swing           107 non-null    float64
 31  squared_up_contact     107 non-null    float64
 32  squared_up_swing       107 non-null    float64
 33  avg_swing_length       107 non-null    float64
 34  swords                 107 non-null    int64
 35  exit_velocity_avg      107 non-null    float64
 36  launch_angle_avg       107 non-null    float64
 37  sweet_spot_percent     107 non-null    float64
 38  barrel_batted_rate     107 non-null    float64
dtypes: float64(24), int64(14), object(1)
memory usage: 32.7+ KB

In [6]:
pitch.describe()

,player_id,year,player_age,p_game,p_formatted_ip,pa,ab,hit,single,double,...,blasts_contact,blasts_swing,squared_up_contact,squared_up_swing,avg_swing_length,swords,exit_velocity_avg,launch_angle_avg,sweet_spot_percent,barrel_batted_rate
count,107.000000,107.0,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,...,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000
mean,632635.616822,2024.0,28.869159,29.420561,160.127103,667.859813,608.177570,146.401869,94.560748,29.140187,...,13.533645,10.418692,32.575701,25.035514,7.324299,19.485981,88.752336,13.608411,34.128037,7.854206
std,53513.052138,0.0,3.731771,3.370341,22.603104,88.539987,84.582751,24.793814,19.175543,7.044935,...,2.169686,1.942821,2.929738,2.946608,0.126522,7.365607,1.162167,4.431919,2.864480,1.504853
min,450203.000000,2024.0,22.000000,21.000000,117.000000,504.000000,453.000000,92.000000,48.000000,14.000000,...,7.600000,5.600000,25.500000,18.400000,7.000000,4.000000,85.700000,0.400000,24.400000,3.300000
25%,607070.500000,2024.0,26.000000,28.000000,141.100000,587.500000,532.000000,130.000000,81.500000,24.000000,...,11.950000,9.050000,30.650000,23.050000,7.200000,15.000000,88.100000,11.300000,32.550000,7.050000
50%,656427.000000,2024.0,28.000000,30.000000,165.100000,692.000000,628.000000,147.000000,94.000000,29.000000,...,13.800000,10.600000,32.700000,24.800000,7.300000,19.000000,88.900000,14.000000,34.500000,8.000000
75%,669449.500000,2024.0,31.500000,32.000000,177.150000,737.000000,667.000000,165.000000,108.000000,34.000000,...,14.950000,11.650000,34.600000,27.450000,7.400000,23.000000,89.600000,16.400000,36.300000,8.850000
max,694973.000000,2024.0,40.000000,42.000000,208.200000,841.000000,783.000000,208.000000,152.000000,51.000000,...,19.500000,15.500000,39.200000,30.900000,7.600000,52.000000,91.200000,25.400000,38.900000,11.000000

In [7]:
pitch.isnull().sum()

last_name, first_name    0
player_id                0
year                     0
player_age               0
p_game                   0
p_formatted_ip           0
pa                       0
ab                       0
hit                      0
single                   0
double                   0
triple                   0
home_run                 0
strikeout                0
walk                     0
k_percent                0
bb_percent               0
batting_avg              0
slg_percent              0
on_base_percent          0
on_base_plus_slg         0
xba                      0
xslg                     0
woba                     0
xwoba                    0
xobp                     0
xiso                     0
avg_swing_speed          0
fast_swing_rate          0
blasts_contact           0
blasts_swing             0
squared_up_contact       0
squared_up_swing         0
avg_swing_length         0
swords                   0
exit_velocity_avg        0
launch_angle_avg         0
sweet_spot_percent       0
barrel_batted_rate       0
dtype: int64